# ── All pizza options & prices ──────────────────────────────────────────────
SIZES = {
    "personal":    ("Personal 6\"",  7.99),
    "small":       ("Small 8\"",     9.99),
    "medium":      ("Medium 12\"",  13.99),
    "large":       ("Large 14\"",   16.99),
    "extra large": ("XL 16\"",      19.99),
    "xl":          ("XL 16\"",      19.99),
}
CRUSTS = {
    "thin":         ("Thin Crust",        0.00),
    "crispy":       ("Crispy Thin",       0.00),
    "thick":        ("Thick Crust",       0.00),
    "hand tossed":  ("Hand Tossed",       0.00),
    "stuffed":      ("Stuffed Crust",     2.50),
    "cauliflower":  ("Cauliflower Crust", 3.00),
    "gluten free":  ("Gluten-Free Crust", 2.50),
    "gluten-free":  ("Gluten-Free Crust", 2.50),
}
SAUCES = {
    "marinara":     ("Marinara",       0.00),
    "tomato":       ("Classic Tomato", 0.00),
    "bbq":          ("BBQ",            0.00),
    "barbecue":     ("BBQ",            0.00),
    "alfredo":      ("Alfredo",        0.50),
    "white":        ("White Alfredo",  0.50),
    "pesto":        ("Basil Pesto",    0.50),
    "ranch":        ("Ranch",          0.00),
    "buffalo":      ("Buffalo",        0.00),
    "garlic butter":("Garlic Butter",  0.00),
}
CHEESES = {
    "no cheese":    ("No Cheese",    0.00),
    "dairy-free":   ("Dairy-Free",   1.50),
    "vegan":        ("Vegan Cheese", 1.50),
    "mozzarella":   ("Mozzarella",   0.00),
    "cheddar":      ("Cheddar",      0.50),
    "parmesan":     ("Parmesan",     0.50),
    "feta":         ("Feta",         1.00),
    "gouda":        ("Gouda",        1.00),
    "ricotta":      ("Ricotta",      0.75),
}
TOPPINGS = {
    # key: (label, emoji, price)
    "pepperoni":        ("Pepperoni",         "🍕", 1.50),
    "mushrooms":        ("Mushrooms",          "🍄", 1.00),
    "mushroom":         ("Mushrooms",          "🍄", 1.00),
    "spinach":          ("Spinach",            "🥬", 1.00),
    "jalapeños":        ("Jalapeños",          "🌶️", 0.75),
    "jalapenos":        ("Jalapeños",          "🌶️", 0.75),
    "jalapeno":         ("Jalapeños",          "🌶️", 0.75),
    "olives":           ("Black Olives",       "🫒", 1.00),
    "black olives":     ("Black Olives",       "🫒", 1.00),
    "bell peppers":     ("Bell Peppers",       "🫑", 1.00),
    "bell pepper":      ("Bell Peppers",       "🫑", 1.00),
    "red onion":        ("Red Onion",          "🧅", 0.75),
    "onion":            ("Red Onion",          "🧅", 0.75),
    "grilled chicken":  ("Grilled Chicken",    "🍗", 2.00),
    "chicken":          ("Grilled Chicken",    "🍗", 2.00),
    "ground beef":      ("Ground Beef",        "🥩", 2.00),
    "beef":             ("Ground Beef",        "🥩", 2.00),
    "sausage":          ("Italian Sausage",    "🌭", 1.75),
    "bacon":            ("Bacon",              "🥓", 1.75),
    "ham":              ("Ham",                "🍖", 1.50),
    "pineapple":        ("Pineapple",          "🍍", 1.00),
    "tomatoes":         ("Fresh Tomatoes",     "🍅", 1.00),
    "tomato":           ("Fresh Tomatoes",     "🍅", 1.00),
    "basil":            ("Fresh Basil",        "🌿", 0.75),
    "garlic":           ("Roasted Garlic",     "🧄", 0.75),
    "roasted garlic":   ("Roasted Garlic",     "🧄", 0.75),
    "arugula":          ("Arugula",            "🥗", 1.00),
    "broccoli":         ("Broccoli",           "🥦", 1.00),
    "corn":             ("Sweet Corn",         "🌽", 0.75),
    "artichoke":        ("Artichoke Hearts",   "🌱", 1.50),
    "anchovies":        ("Anchovies",          "🐟", 1.50),
    "anchovy":          ("Anchovies",          "🐟", 1.50),
    "avocado":          ("Avocado",            "🥑", 1.50),
    "prosciutto":       ("Prosciutto",         "🍖", 2.50),
    "truffle":          ("Truffle Oil",        "✨", 3.00),
    "feta":             ("Feta Crumbles",      "🧀", 1.25),
    "zucchini":         ("Zucchini",           "🥒", 1.00),
    "sun dried tomato": ("Sun-Dried Tomatoes", "☀️", 1.25),
}
EXTRAS = {
    "extra cheese": ("Extra Cheese", 1.50),
    "extra sauce":  ("Extra Sauce",  0.50),
    "well done":    ("Well Done",    0.00),
    "light sauce":  ("Light Sauce",  0.00),
}
TAX_RATE = 0.13